### ISSUE TITLE
Plot/export solution at specified spatial points

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#23]
I'd like to plot/export data at user specified spatial points.
How would I go about getting an output of, say, "Er", at (r,z)=(0.5, 0.0) in a EM2Da namespace? I assume the plotting tab "Points" or "Probe" has to be used, but I'm not sure what the correct user input should be.

**Comment by sshiraiwa** [comment]
@bbiswas-plasma 
An easy way is to make a boundary plot first, and then export it. in piScope, you can right click
the curve or image in plot and choose export from the pull down menu. This way, you can export
the data used in the plot in the python shell. Figure in piScope also has export menu, where you 
can save the data to an HDF file. 

FYI, probe is to show the data from the probe you set in the simulation. Usually, this is used for
time-dependent simulation. Point is in fact closer to what you are looking for but this is meant
mostly extract a data for 3D simulation.

**Comment by bbiswas-plasma** [comment]
Ok, following your suggestion, I was successfully able to export the data from a boundary plot.
Thanks.
