### ISSUE TITLE
Changing incoming_amp gives unexpected answer for Coax(TEM) port

### ISSUE THREAD

**Issue by eleppink** [piScope/PetraM_Base#25]
For the Coax(TEM) port, if incoming_amp is changed to a value that is not 1.0, the power in the port (calculated by the time-averaged integral of the Poynting vector), gives unexpected answers.

For example, when testing a simple coax model with incoming_amp=1.0, the integral of the Poynting vector gives 1.0 W, as expected.
But when incoming_amp=100, the integral of the Poynting vector gives roughly 31 W. I would expect 100 W.
And for incoming_amp=1000, the integral of the Poynting vector gives roughly 280 W. I would expect 1000 W.

**Comment by sshiraiwa** [comment]
Thank you @eleppink. Indeed, this is a normalization bug. I updated RF module to fix it. Please check if it works now.
