### ISSUE TITLE
MUMPS direct solve fails for DoF~13m

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#26]
I'm trying to run a C-Mod LH case, where DoF~13m.
Directory: /home/biswas/myscratch/mfem_batch/r_em2da_cmod_lh_na4e19_2x_order3_redo

Using the direct solver method with MUMPS, I get the following error:

```
** Error/warning return ** from Analysis *  INFO(1:2)= -51           -2290

 Elapsed time in analysis driver=     124.4199
 ** ERROR RETURN ** FROM ZMUMPS INFO(1)=  -51
```
This has 3rd order elements. Note that if I use 2nd order elements (DoF~9m), the direct solve is successful.
Is this is a case of the matrix being too large for direct solve? I'm pretty sure the solver isn't running out of memory (according to the memory_report.o that's generated).

If this problem is indeed too large for direct solve, do you recommend the use of an iterative solver?

**Comment by sshiraiwa** [comment]
See MUMPS manual for the meaning of -51 (http://mumps-solver.org)
You can increase the log level of MUMPS solver to dump out its memory usage.
On the cluster (if you are running there), there is memory report to check if memory is sufficient.

**Comment by bbiswas-plasma** [comment]
This issue was resolved by going to a 64-bit machine (Cori), which could handle the larger mapping needed for this problem size.
