### ISSUE TITLE
Post-processing: vector operations

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#28]
For the post-processing step, does Petra-M include built-in functions to calculate the div/grad/curl of the solution fields? 

I was able to use the python library “numdifftools” to calculate these fields, but wanted to check if there was a simpler/recommended way.

**Comment by sshiraiwa** [comment]
DiscreteLinearInterpolater can be used in Postprocessing. If your operation needs
a linear solve, you need to extend the Physics model to include such a calculation
in a solve stage. 

Also, for 2D, one need to be careful to take care of coordinate transformation. 

—
S
