### ISSUE TITLE
Can't submit job to cluster

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#35]
I noticed there was recently a change in Piscope/Petra-M to the cluster job-submission window.

I think this has caused a bug in the Cluster -> Solve window. In the  “Queue” box, it says “failed to read queue config.”

I went to Cluster -> settings and reloaded (and also remade) the eofe connection. But the error persists. The same is true for cori.
Thanks,
Bodhi

**Comment by sshiraiwa** [comment]
Indeed, there is an update which allows you (for example) to receive E-mail
notification when job starts (or ends).

Cori is in the maintenance today. Can you try it with MIT cluster, again? 
Note that you need to choose at least one keyword and write submission 
message for logging.

—
Syun'ichi

**Comment by bbiswas-plasma** [comment]
Neat. I look forward to using the notification feature.

Just tried it, and I again got “failed to read queue config”. This was after I restarted Piscope.
-Bodhi

**Comment by sshiraiwa** [comment]
Something is wrong, Let’s talk off-line.

—
S
