### ISSUE TITLE
Right-click not working in model tree

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#39]
In the Model Tree window, I am unable to right click on Geometry->GmshGeomX or any of the geometric elements under that heading. Instead of getting the usual window of right-click options (ex. enable/disable), I instead get the following error message in terminal:

`
Traceback (most recent call last):
  File "/home/shiraiwa/twopi_roots/20190713_py3/lib/python3.6/site-packages/PetraM_Base-1.1.4-py3.6.egg/petram/pi/dlg_edit_model.py", line 265, in OnItemRightClick
    for t, m, m2 in mm.get_special_menu(e):
TypeError: get_special_menu() takes 1 positional argument but 2 were given
`

**Comment by sshiraiwa** [comment]
Can you point me the project file?

**Comment by bbiswas-plasma** [comment]
I've noticed this error on 3 out of 3 different piscope projects so far, so I'm guessing its common to all of them.

Feel free to look at the following project where I have confirmed this error exists:
/home/biswas/Documents/petram_tutorial/cmod_icrf_example_exact.pfz

**Comment by bbiswas-plasma** [comment]
Some additional info that may help.
1) I'm on mferws01. Before running piscope, I am running the following script: "/home/shiraiwa/twopi_roots/20190713_py3/bin/activate_twopi"

2) I started a new project in Piscope, and launched Petra-M using the command 'petram()'.
In this new model tree, I can successfully right-click Geometry and add a new Gmesh geometry called 'GmshGeom1'. Then, when I right-click on 'GmshGeom1' this error happens.

**Comment by sshiraiwa** [comment]
Please try it again,

**Comment by bbiswas-plasma** [comment]
The problem seems resolved on my end. Right-clicking on GmshGeom elements in the model tree works as expected. Thanks.
