### ISSUE TITLE
Periodic BC for EM2D

### ISSUE THREAD

**Issue by bbiswas-plasma** [piScope/PetraM_Base#67]
@sshiraiwa 
If I remember correctly, the option to add a periodic BC is available by right-clicking on the "Boundary" drop-down in the Petra-M model tree editor. I can't find it for EM2D (see attached pic).
![Screen Shot 2021-04-13 at 1 32 39 PM](https://user-images.githubusercontent.com/66182110/114596669-e7378880-9c5d-11eb-9590-7e1602fc4586.png)

I do, however, see that it's available for the 'WF' physics model, though I can't recall what that means. It's been a while since you showed me how to use the periodic BC in Petra-M. Sorry if I'm mis-remembering things!

**Comment by sshiraiwa** [comment]
Isn't it supposed to be under "Pair"?

**Comment by bbiswas-plasma** [comment]
under "pair" I only see the "add Floquet" option. Is this the periodic BC condition I should use? If so, I am confused as to what the "u mapping" option is. And I assume that the phase=0 option should be used so that the solution is continuous at the periodic boundary?
